version: "3"
services:
  ipfs_node:
    image: ipfs/go-ipfs:v0.8.0
    volumes:
      - ~/ipfs/ipfs_staging:/export
      - ~/ipfs/ipfs_data:/data/ipfs
    ports:
      - "5001:5001"
      - "8081:8080"
      - "4001:4001"

  feecc_io_gateway:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    links:
      - ipfs_node:ipfs
